stages:
  - build
  - release

Build Dev:
  stage: build
  tags:
    - develop
  before_script:
    - export COMPOSE_PROJECT_NAME=${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}
    - export BRANCH_NAME=${CI_COMMIT_REF_NAME}
    - export MYSQL_ROOT_PASSWORD=zxeXHZpy9ofW
    - export BITRIX_DIR=/home/gitlab-runner/project/medicina-pricelist/bitrix
    - export UPLOAD_DIR=/home/gitlab-runner/project/medicina-pricelist/upload
    - export COMPOSE_INTERACTIVE_NO_CLI=1
  script:
    - export HTTP_PORT="$(/home/gitlab-runner/nginx2docker/nginx2docker.py freeport $CI_COMMIT_REF_NAME.$CI_PROJECT_NAME.itpeople.dev)"
    - export MYSQL_PORT="$(/home/gitlab-runner/nginx2docker/nginx2docker.py freeport null 1)"
    - touch "$(pwd)/.env"
    - echo "MYSQL_HOST=mysql" >> "$(pwd)/.env"
    - echo "MYSQL_USER=root" >> "$(pwd)/.env"
    - echo "MYSQL_PASSWORD=$MYSQL_ROOT_PASSWORD" >> "$(pwd)/.env"
    - echo "MYSQL_DATABASE=medicina_pricelist" >> "$(pwd)/.env"
    - echo "DEBUG=true" >> "$(pwd)/.env"
#    - less "$(pwd)/.env"
    - docker-compose -p $COMPOSE_PROJECT_NAME -f docker-compose.yml -f docker-compose-dev.yml up -d --build --force-recreate
    - docker exec -i ${COMPOSE_PROJECT_NAME}_mysql_1 /bin/bash -c "mysql -uroot --password='${MYSQL_ROOT_PASSWORD}'" < ./.docker/mysql/dump.sql
    - /home/gitlab-runner/nginx2docker/nginx2docker.py add-to-pool $CI_COMMIT_REF_NAME.$CI_PROJECT_NAME.itpeople.dev null $HTTP_PORT
    - "echo Ссылка на сборку: https://${CI_COMMIT_REF_NAME}.${CI_PROJECT_NAME}.itpeople.dev"
  only:
    refs:
      - master
      - dev
      - /^hotfix-.*$/
      - /^release-.*$/
      - /^feature-.*$/

Build Prod:
  stage: build
  tags:
    - develop
  before_script:
    - export BRANCH_NAME=${CI_COMMIT_REF_NAME}
    - export HOST_MACHINE_IP=178.159.249.31
    - export BITRIX_DIR=/home/gitlab-runner/project/medicina-pricelist/bitrix
    - export UPLOAD_DIR=/home/gitlab-runner/project/medicina-pricelist/upload
    - export COMPOSE_INTERACTIVE_NO_CLI=1
    - docker login gitlab.itpeople.dev:4567 -u desin@itpeople.ru -p $ACCESS_TOKEN
  script:
    - export HTTP_PORT=80
    - export COMPOSE_PROJECT_NAME=production_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${HTTP_PORT}
    - touch "$(pwd)/.env"
    - echo "MYSQL_HOST=mysql" >> "$(pwd)/.env"
    - echo "MYSQL_USER=$MYSQL_USER" >> "$(pwd)/.env"
    - echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> "$(pwd)/.env"
    - echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> "$(pwd)/.env"
#    - echo "DEBUG=true" >> "$(pwd)/.env"
#    - less "$(pwd)/.env"
    - docker-compose -p $COMPOSE_PROJECT_NAME -f docker-compose.yml -f docker-compose-prod.yml build
    - docker-compose -p $COMPOSE_PROJECT_NAME -f docker-compose.yml -f docker-compose-prod.yml push
    - docker logout
  only:
    - master
  when: manual


Release Prod:
  stage: release
  tags:
    - medicina1
  before_script:
    - export BRANCH_NAME=${CI_COMMIT_REF_NAME}
    - export HOST_MACHINE_IP=178.159.249.31
    - export BITRIX_DIR=/home/gitlab-runner/project/medicina-pricelist/bitrix
    - export UPLOAD_DIR=/home/gitlab-runner/project/medicina-pricelist/upload
    - export COMPOSE_INTERACTIVE_NO_CLI=1
    - docker login gitlab.itpeople.dev:4567 -u desin@itpeople.ru -p $ACCESS_TOKEN
  script:
    - export HTTP_PORT="$(/home/gitlab-runner/nginx2docker/nginx2docker.py freeport null)"
    - export COMPOSE_PROJECT_NAME=production_${CI_PROJECT_NAME}_${CI_COMMIT_REF_NAME}_${HTTP_PORT}
    - touch "$(pwd)/.env"
    - echo "MYSQL_HOST=mysql" >> "$(pwd)/.env"
    - echo "MYSQL_USER=$MYSQL_USER" >> "$(pwd)/.env"
    - echo "MYSQL_PASSWORD=$MYSQL_PASSWORD" >> "$(pwd)/.env"
    - echo "MYSQL_DATABASE=$MYSQL_DATABASE" >> "$(pwd)/.env"
#    - echo "DEBUG=true" >> "$(pwd)/.env"
#    - less "$(pwd)/.env"
    - docker-compose -p $COMPOSE_PROJECT_NAME -f docker-compose.yml -f docker-compose-prod.yml pull
    - docker-compose -p $COMPOSE_PROJECT_NAME -f docker-compose.yml -f docker-compose-prod.yml up -d --force-recreate
    - docker logout
    - "echo Новый порт: ${HTTP_PORT}"
  only:
    - master
  when: manual